services:
  recipes.api:
    image: recipes.api
    build:
      context: .
      dockerfile: src/Recipes.Api/Dockerfile
    
  recipes.db:
    image: postgres:13
    environment:
      POSTGRES_USER: recipes
      POSTGRES_PASSWORD: recipes
      POSTGRES_DB: recipes
    ports:
      - "5432:5432"
    volumes:
      - recipes.db:/var/lib/postgresql/data
      - /resources:/resources

volumes:
  recipes.db: